### PR TITLE
Automodel refactor, in_batch_negatives

### PR DESCRIPTION
**Pull request by ronakice**
Changes
- add AutoModel, AutoTokenizer, etc, so that scripts can automatically load any of the models available in Transformers (earlier we had to keep adding to the training/eval scripts)
- add in_batch_negative feature for training (where both positive and negative passages for the same query are part of the same batch)
- rename run_numbert_tfrecord.py to run_numbert.py ( delete old run_numbert.py as it is in encompassed by this)
- remove awkward "FAST_TOKENIZERS" boolean (now automatically chooses best available tokenization method).
- modify the training script to look as close as the script provided by transformers for GLUE (while also having the additional functionalities already included in the project)
- switch .content field in result from pyserini's SimpleSearch to .raw (required as .content doesn't work anymore)

### CODE REVIEW

**Comment by ronakice** [comment]
Collab seems to work fine for both MARCO/TREC

**Review by rodrigonogueira4 — APPROVED** [review]
This is great, thanks for improving the code!

**Comment by rodrigonogueira4** [comment]
Fell free to merge when you think it is ready. Also, could you please add me as a collaborator?

**Comment by ronakice** [comment]
Added you. Sorry, I forgot!

**Pull request merged**
